/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javacrud.view;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.DirectoryStream.Filter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javacrud.control.ImageDAO;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author r.bessede
 */
public class SelectAvatar extends javax.swing.JDialog {

    private final int largeurIn = 420;
    private final int hauteurIn = 495;
    private final int largeurOut = 140;
    private final int hauteurOut = 165;
    private final int maxFileSize = 5000000;
    private String pseudo;
    private boolean selected;

    /**
     * Creates new form SelectAvatar
     */
    public SelectAvatar(java.awt.Frame parent, boolean modal, String pseudo) {
        super(parent, modal);
        this.pseudo = pseudo;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageChooser = new javax.swing.JFileChooser();
        avatar = new javax.swing.JLabel();
        Choisir = new javax.swing.JButton();
        valider = new javax.swing.JButton();
        abandonner = new javax.swing.JButton();
        miniature = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/user-tie-max.jpg"))); // NOI18N

        Choisir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/folder-open_20.png"))); // NOI18N
        Choisir.setText("Choisir");
        Choisir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChoisirMouseClicked(evt);
            }
        });

        valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/valid_20.png"))); // NOI18N
        valider.setText("Valider");
        valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validerMouseClicked(evt);
            }
        });

        abandonner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/escape_20.png"))); // NOI18N
        abandonner.setText("Abandonner");
        abandonner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abandonnerMouseClicked(evt);
            }
        });

        miniature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/user-tie-min.jpg"))); // NOI18N
        miniature.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Choisir)
                        .addGap(18, 18, 18)
                        .addComponent(valider)
                        .addGap(18, 18, 18)
                        .addComponent(abandonner)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(avatar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(miniature, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar)
                    .addComponent(miniature))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Choisir)
                    .addComponent(valider)
                    .addComponent(abandonner))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChoisirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChoisirMouseClicked
        ImageIcon photo = null;
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "png", "jpg", "jpeg", "gif");
        imageChooser.setCurrentDirectory(FileSystemView.getFileSystemView().getHomeDirectory());
        imageChooser.setFileFilter(filter);
        int returnValue = imageChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedImg = imageChooser.getSelectedFile();
            if (selectedImg.length() < maxFileSize) {
                try {
                    photo = ImageDAO.importImage(selectedImg.getPath(), largeurIn, hauteurIn);
                } catch (IOException ex) {
                    Logger.getLogger(SelectAvatar.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (photo != null) {
                    this.avatar.setIcon(photo);
                    try {
                        photo = ImageDAO.importImage(selectedImg.getPath(), largeurOut, hauteurOut);
                    } catch (IOException ex) {
                        Logger.getLogger(SelectAvatar.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    this.miniature.setIcon(photo);
                } else {
                    this.avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/user-tie.jpg")));
                }
            }
        }
    }//GEN-LAST:event_ChoisirMouseClicked

    private void validerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerMouseClicked
        ImageDAO.setUtImage(pseudo, (ImageIcon) this.miniature.getIcon());
        this.selected = true;
        this.dispose();

    }//GEN-LAST:event_validerMouseClicked

    private void abandonnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abandonnerMouseClicked
        this.selected = false;
        this.dispose();
    }//GEN-LAST:event_abandonnerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectAvatar dialog = new SelectAvatar(new javax.swing.JFrame(), true, "Etudiant");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Choisir;
    private javax.swing.JButton abandonner;
    private javax.swing.JLabel avatar;
    private javax.swing.JFileChooser imageChooser;
    private javax.swing.JLabel miniature;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
