/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacrud.view;

import com.mysql.cj.xdevapi.Statement;
import javacrud.model.Utilisateur;
import javacrud.model.Commune;
import javacrud.tech.UtilDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javacrud.control.UtilisateurDAOImp;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import javacrud.control.ImageDAO;
import javax.swing.ImageIcon;

/**
 *
 * @author r.bessede
 */
public class UtilCrud extends javax.swing.JFrame {

    /**
     * Creates new form UtilCrud
     */
    Connection con;
    Statement st;
    public TreeMap<String, Utilisateur> lesUtilisateurs = new TreeMap<String, Utilisateur>();
    public UtilisateurDAOImp dao = new UtilisateurDAOImp();
    Utilisateur util = new Utilisateur();
    String uiNumpost;
    private Commune selectedVille;
    private Commune laVille;

    public UtilCrud() {
        initComponents();
        message.setText("Veuiller choisir un utilisateur dans le tableau de droite ou saisir les données à créer");
        chargerLesUtilisateurs();
    }

    private void chargerLesUtilisateurs() {
        lesUtilisateurs.clear();
        lesUtilisateurs = dao.list();
        //System.out.println(lesUtilisateurs.size());
        chargerTableauUtilisateurs();
    }

    private void chargerTableauUtilisateurs() {
        DefaultTableModel uiTable = (DefaultTableModel) tbUtilisateur.getModel();

        int j = uiTable.getRowCount();
        //System.out.println(j);
        for (int i = j - 1; i >= 0; i--) {
            uiTable.removeRow(i);;
        }

        for (String pseudo : lesUtilisateurs.keySet()) {
            Utilisateur unUtilisateur = lesUtilisateurs.get(pseudo);
            Object[] row = new Object[3];
            row[0] = unUtilisateur.getUt_nom();
            row[1] = unUtilisateur.getUt_prenom();
            row[2] = unUtilisateur.getUt_pseudo();

            uiTable.addRow(row);
        }
    }

    public void changeSelectUt() {
        int i = tbUtilisateur.getSelectedRow();

        TableModel model = tbUtilisateur.getModel();
        Utilisateur unUtilisateur = lesUtilisateurs.get(model.getValueAt(i, 2).toString());
        uiNom.setText(unUtilisateur.getUt_nom());
        uiPrenom.setText(unUtilisateur.getUt_prenom());
        uiPseudo.setText(unUtilisateur.getUt_pseudo());
        uiMail.setText(unUtilisateur.getUt_mail());
        uiMP.setText(unUtilisateur.getUt_mp());
        //uiPhrase.setText(unUtilisateur.getUt_phrase());
        uiAdr1.setText(unUtilisateur.getUt_adr1());
        uiAdr2.setText(unUtilisateur.getUt_adr2());
        uiCdpost.setText(unUtilisateur.getUt_cdpost());
        uiCommune.setText(unUtilisateur.getNom_Commune());
        
        chargePhotoUt();
    }

    public void alert(String msg) {
        JOptionPane.showMessageDialog(rootPane, msg);
        message.setForeground(new java.awt.Color(51, 102, 0));
        message.setText(msg);
    }

    public void alert(String msg, String titre) {
        JOptionPane.showMessageDialog(rootPane, msg, titre, JOptionPane.ERROR_MESSAGE);
        message.setForeground(new java.awt.Color(204, 0, 51));
        message.setText(msg);
    }

    public void chargePhotoUt() {
        ImageIcon photo = ImageDAO.getUtIcon(this.uiPseudo.getText());
        if (photo != null) {
            this.avatar.setIcon(photo);
        } else {
            this.avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/ressource/user-tie_.jpg")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelSaisie = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        uiNom = new javax.swing.JTextField();
        jLabelPrenom = new javax.swing.JLabel();
        uiPrenom = new javax.swing.JTextField();
        jLabelPseudo = new javax.swing.JLabel();
        uiPseudo = new javax.swing.JTextField();
        jLabelMail = new javax.swing.JLabel();
        uiMail = new javax.swing.JTextField();
        jLabelMP = new javax.swing.JLabel();
        uiMP = new javax.swing.JTextField();
        Creer = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        Vider = new javax.swing.JButton();
        ChercheVille = new javax.swing.JButton();
        uiPhrase = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uiAdr1 = new javax.swing.JTextField();
        uiAdr2 = new javax.swing.JTextField();
        uiCdpost = new javax.swing.JTextField();
        uiCommune = new javax.swing.JTextField();
        photo = new javax.swing.JButton();
        avatar = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        tbScrollPane = new javax.swing.JScrollPane();
        tbUtilisateur = new javax.swing.JTable();
        Entete = new javax.swing.JLabel();
        Aide = new javax.swing.JButton();
        Parametre = new javax.swing.JButton();
        Mailer = new javax.swing.JButton();
        Quitter = new javax.swing.JButton();
        AuSujet = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(825, 500));
        getContentPane().setLayout(null);

        jPanelSaisie.setOpaque(false);

        jLabelNom.setText("Nom");

        jLabelPrenom.setText("Prénom");

        uiPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiPrenomActionPerformed(evt);
            }
        });

        jLabelPseudo.setText("Utilisateur");

        jLabelMail.setText("Mail");

        uiMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiMailActionPerformed(evt);
            }
        });

        jLabelMP.setText("Mot de Passe");

        Creer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/plus_20.png"))); // NOI18N
        Creer.setText("Creer");
        Creer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreerMouseClicked(evt);
            }
        });
        Creer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreerActionPerformed(evt);
            }
        });

        Modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/pencil_20.png"))); // NOI18N
        Modifier.setText("Modifier");
        Modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifierMouseClicked(evt);
            }
        });

        Supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/minus_20.png"))); // NOI18N
        Supprimer.setText("Supprimer");
        Supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupprimerMouseClicked(evt);
            }
        });

        Vider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/eye-slash_20.png"))); // NOI18N
        Vider.setText("Nouveau");
        Vider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViderMouseClicked(evt);
            }
        });

        ChercheVille.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/eye_20.png"))); // NOI18N
        ChercheVille.setText("Ville");
        ChercheVille.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChercheVilleMouseClicked(evt);
            }
        });

        uiPhrase.setText("Adresse");

        jLabel3.setText("Code Postal");

        uiAdr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiAdr1ActionPerformed(evt);
            }
        });

        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/user-img_20.png"))); // NOI18N
        photo.setText("Photo");
        photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                photoMouseClicked(evt);
            }
        });
        photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoActionPerformed(evt);
            }
        });

        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/user-tie-min.jpg"))); // NOI18N
        avatar.setText("jLabel2");
        avatar.setMaximumSize(new java.awt.Dimension(142, 142));
        avatar.setMinimumSize(new java.awt.Dimension(167, 167));

        javax.swing.GroupLayout jPanelSaisieLayout = new javax.swing.GroupLayout(jPanelSaisie);
        jPanelSaisie.setLayout(jPanelSaisieLayout);
        jPanelSaisieLayout.setHorizontalGroup(
            jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaisieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uiCdpost, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelSaisieLayout.createSequentialGroup()
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPseudo)
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addComponent(jLabelMP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uiMP, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addComponent(uiPhrase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uiAdr2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uiAdr1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelMail)
                        .addGap(18, 18, 18)
                        .addComponent(uiMail, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addComponent(jLabelPrenom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uiPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uiPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addComponent(jLabelNom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uiNom, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSaisieLayout.createSequentialGroup()
                                .addComponent(ChercheVille)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(uiCommune))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSaisieLayout.createSequentialGroup()
                                .addComponent(Modifier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Creer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Supprimer)))
                        .addGap(18, 18, 18)
                        .addComponent(Vider)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSaisieLayout.createSequentialGroup()
                        .addComponent(photo)
                        .addContainerGap())
                    .addComponent(avatar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelSaisieLayout.setVerticalGroup(
            jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaisieLayout.createSequentialGroup()
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(photo)
                            .addComponent(uiPhrase)
                            .addComponent(uiAdr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uiAdr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPseudo)
                                    .addComponent(uiPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMP)
                                    .addComponent(uiMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNom)
                                    .addComponent(uiNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPrenom)
                                    .addComponent(uiPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMail)
                            .addComponent(uiMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(uiCdpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Supprimer)
                    .addComponent(Modifier)
                    .addComponent(Creer)
                    .addComponent(Vider))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChercheVille)
                    .addComponent(uiCommune, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelSaisie);
        jPanelSaisie.setBounds(340, 80, 590, 380);

        message.setText("jLabel2");
        getContentPane().add(message);
        message.setBounds(10, 450, 400, 20);

        tbUtilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prénom", "Utilisateur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUtilisateur.setOpaque(false);
        tbUtilisateur.setSelectionBackground(new java.awt.Color(255, 51, 51));
        tbUtilisateur.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbUtilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUtilisateurMouseClicked(evt);
            }
        });
        tbUtilisateur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbUtilisateurKeyReleased(evt);
            }
        });
        tbScrollPane.setViewportView(tbUtilisateur);
        if (tbUtilisateur.getColumnModel().getColumnCount() > 0) {
            tbUtilisateur.getColumnModel().getColumn(1).setResizable(false);
            tbUtilisateur.getColumnModel().getColumn(2).setResizable(false);
        }
        tbUtilisateur.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(tbScrollPane);
        tbScrollPane.setBounds(10, 80, 310, 350);

        Entete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/java_64.png"))); // NOI18N
        Entete.setText("CRUD SIMPLIFIE : GESTION DES UTILISATEURS ET AUTRES RESSOURCES");
        getContentPane().add(Entete);
        Entete.setBounds(0, 0, 800, 60);

        Aide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/question-circle_20.png"))); // NOI18N
        Aide.setText("Aide");
        Aide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AideMouseClicked(evt);
            }
        });
        getContentPane().add(Aide);
        Aide.setBounds(760, 480, 78, 26);

        Parametre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/wrench._20.png"))); // NOI18N
        Parametre.setText("Paramètre");
        Parametre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParametreMouseClicked(evt);
            }
        });
        getContentPane().add(Parametre);
        Parametre.setBounds(10, 480, 140, 26);

        Mailer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/envelope_20.png"))); // NOI18N
        Mailer.setText("Mail");
        Mailer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MailerMouseClicked(evt);
            }
        });
        getContentPane().add(Mailer);
        Mailer.setBounds(570, 480, 77, 26);

        Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/escape_20.png"))); // NOI18N
        Quitter.setText("Quitter");
        Quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitterMouseClicked(evt);
            }
        });
        getContentPane().add(Quitter);
        Quitter.setBounds(850, 480, 91, 26);

        AuSujet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/info-circle_20.png"))); // NOI18N
        AuSujet.setText("Au Sujet");
        AuSujet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AuSujetMouseClicked(evt);
            }
        });
        getContentPane().add(AuSujet);
        AuSujet.setBounds(650, 480, 98, 26);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/back_ec.jpg"))); // NOI18N
        Background.setText("jLabel2");
        getContentPane().add(Background);
        Background.setBounds(0, 70, 950, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreerActionPerformed

    private void uiPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiPrenomActionPerformed

    private void uiAdr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiAdr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiAdr1ActionPerformed

    private void QuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitterMouseClicked
        System.exit(0);
    }//GEN-LAST:event_QuitterMouseClicked

    private void tbUtilisateurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbUtilisateurKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbUtilisateurKeyReleased

    private void tbUtilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUtilisateurMouseClicked
        // TODO add your handling code here:
        changeSelectUt();
    }//GEN-LAST:event_tbUtilisateurMouseClicked

    private void ViderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViderMouseClicked
        // TODO add your handling code here:
        uiNom.setText(null);
        uiPrenom.setText(null);
        uiPseudo.setText(null);
        uiMail.setText(null);
        uiMP.setText(null);
        //uiPhrase.setText(unUtilisateur.getUt_phrase());
        uiAdr1.setText(null);
        uiAdr2.setText(null);
        uiCdpost.setText(null);
        uiCommune.setText(null);

    }//GEN-LAST:event_ViderMouseClicked

    private void MailerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MailerMouseClicked
        // TODO add your handling code here:
        Utilisateur unUtil = new Utilisateur();
        System.out.println(unUtil.getUt_mail());
        try {
            new Mail(uiMail.getText()).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(UtilCrud.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MailerMouseClicked

    private void AuSujetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AuSujetMouseClicked
        // TODO add your handling code here:
        About auSujet = new About();
        auSujet.setVisible(true);
    }//GEN-LAST:event_AuSujetMouseClicked

    private void AideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AideMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AideMouseClicked

    private void CreerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreerMouseClicked
        // TODO add your handling code here:
        Utilisateur unUtil = new Utilisateur();

        String mp = uiMP.getText();
        String phrase = unUtil.updateUtMp(mp);

        unUtil.setUt_pseudo(uiPseudo.getText().strip());
        unUtil.setUt_nom(uiNom.getText().strip());
        unUtil.setUt_prenom(uiPrenom.getText().strip());
        unUtil.setUt_mp(uiMP.getText().strip());
        unUtil.setUt_phrase(phrase);
        unUtil.setUt_mail(uiMail.getText().strip());
        unUtil.setUt_adr1(uiAdr1.getText().strip());
        unUtil.setUt_adr2(uiAdr2.getText().strip());
        unUtil.setUt_cdpost(uiCdpost.getText().strip());
        unUtil.setUt_numpost(uiNumpost);

        lesUtilisateurs.put(unUtil.getUt_pseudo(), unUtil);

        chargerTableauUtilisateurs();
        dao.create(unUtil);
    }//GEN-LAST:event_CreerMouseClicked

    private void ModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierMouseClicked

        Utilisateur unUtil = new Utilisateur();

        String mp = uiMP.getText();
        String phrase = unUtil.updateUtMp(mp);

        unUtil.setUt_nom(uiNom.getText().strip());
        unUtil.setUt_prenom(uiPrenom.getText().strip());
        unUtil.setUt_mp(uiMP.getText().strip());
        unUtil.setUt_mail(uiMail.getText().strip());
        unUtil.setUt_phrase(phrase);
        unUtil.setUt_adr1(uiAdr1.getText().strip());
        unUtil.setUt_adr2(uiAdr2.getText().strip());
        unUtil.setUt_cdpost(uiCdpost.getText().strip());
        unUtil.setUt_numpost(uiNumpost);
        unUtil.setUt_pseudo(uiPseudo.getText().strip());

        lesUtilisateurs.put(unUtil.getUt_pseudo(), unUtil);

        chargerTableauUtilisateurs();
        dao.update(unUtil);

    }//GEN-LAST:event_ModifierMouseClicked

    private void SupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupprimerMouseClicked
        // TODO add your handling code here:
        int i = tbUtilisateur.getSelectedRow();
        TableModel model = tbUtilisateur.getModel();
        Utilisateur perso = new Utilisateur();

        String pseudo = uiPseudo.getText();
        dao.delete(pseudo);
        lesUtilisateurs.remove(pseudo);
        chargerTableauUtilisateurs();
    }//GEN-LAST:event_SupprimerMouseClicked

    private void ChercheVilleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChercheVilleMouseClicked
        // TODO add your handling code here:
        String cdPost = uiCdpost.getText().strip();
        if (cdPost.matches("[0-9]+") && cdPost.length() == 5) {
            try {
                SelectVille selVille = new SelectVille(new javax.swing.JFrame(), true, Integer.parseInt(cdPost), uiNumpost);
                selVille.setVisible(true);
                this.selectedVille = selVille.getSelectVille();
                if (selVille.isSelected()) {
                    uiNumpost = this.selectedVille.getNum_Postal();
                    uiCommune.setText(this.selectedVille.getNom_Commune());
                }
            } catch (Exception ex) {
                Logger.getLogger(UtilCrud.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            alert("Saisir un code postal correct (5 chiffres) avant de sélectionner la ville !");
        }
    }//GEN-LAST:event_ChercheVilleMouseClicked

    private void ParametreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParametreMouseClicked
        Parametre p;
        try {
            p = new Parametre(new javax.swing.JFrame(), true);
            p.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(UtilCrud.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ParametreMouseClicked

    private void uiMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiMailActionPerformed

    private void photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoActionPerformed

    private void photoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoMouseClicked
        SelectAvatar sa;
        Boolean photo = true;
        try {
            sa = new SelectAvatar(new javax.swing.JFrame(), true, uiPseudo.getText());
            sa.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(UtilCrud.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_photoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UtilCrud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aide;
    private javax.swing.JButton AuSujet;
    private javax.swing.JLabel Background;
    private javax.swing.JButton ChercheVille;
    private javax.swing.JButton Creer;
    private javax.swing.JLabel Entete;
    private javax.swing.JButton Mailer;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Parametre;
    private javax.swing.JButton Quitter;
    private javax.swing.JButton Supprimer;
    private javax.swing.JButton Vider;
    private javax.swing.JLabel avatar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMP;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelPseudo;
    private javax.swing.JPanel jPanelSaisie;
    private javax.swing.JLabel message;
    private javax.swing.JButton photo;
    private javax.swing.JScrollPane tbScrollPane;
    private javax.swing.JTable tbUtilisateur;
    private javax.swing.JTextField uiAdr1;
    private javax.swing.JTextField uiAdr2;
    private javax.swing.JTextField uiCdpost;
    private javax.swing.JTextField uiCommune;
    private javax.swing.JTextField uiMP;
    private javax.swing.JTextField uiMail;
    private javax.swing.JTextField uiNom;
    private javax.swing.JLabel uiPhrase;
    private javax.swing.JTextField uiPrenom;
    private javax.swing.JTextField uiPseudo;
    // End of variables declaration//GEN-END:variables
}
